---
language: node_js

env:
  global:
    - TRIALSCOPE_TOKEN=FNXUB6kjzAgGcQhJW5fxi1nM

node_js:
  - "12"

cache: npm

script:
  - npm install
  - npm install codecov -g
  - npm run lint
  - npm run-script coverage

after_success:
  - codecov
