---
language: node_js

env:
  global:
    - TRIALSCOPE_TOKEN=fake_token

node_js:
  - "12"

cache: npm

script:
  - npm install
  - npm install codecov -g
  - npm run lint
  - npm run-script coverage


after_success:
  - codecov
