---
language: node_js

env:
  global:
    - TRIALSCOPE_TOKEN=fake_token

node_js:
  - "12"

cache: npm

script:
  - npm install 
  - npm run lint
  - npm test

before_install: 
  - cd spec/data
  - curl https://storage.googleapis.com/ig-build/org.hl7.fhir.validator.jar  --output org.hl7.fhir.validator.jar