---
language: node_js

env:
  global:
    - TRIALSCOPE_TOKEN=fake_token

node_js:
  - "12"

cache: npm

script:
  - npm run lint
  - npm test
before_install: 
  - mkdir src/AllPublicXML
  - mkdir src/AllPublicXML/NCT0358xxxx
  - mv spec/support/NCT03587740.xml src/AllPublicXML/NCT0358xxxx